// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Sprint struct {
	SprintID  int32
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	WordCount int32
	Xp        int32
}

type User struct {
	UserID          string
	UserName        string
	ServerName      string
	DifficultyLevel int32
}
