// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sprint_start.sql

package database

import (
	"context"
)

const startSprint = `-- name: StartSprint :exec
INSERT INTO users (user_ID, user_name, server_name)
VALUES ($1 || '\\' || $2, $1, $2)
ON CONFLICT (user_ID) DO UPDATE
    SET user_name = EXCLUDED.user_name
`

type StartSprintParams struct {
	UserName   string
	ServerName string
}

func (q *Queries) StartSprint(ctx context.Context, arg StartSprintParams) error {
	_, err := q.db.ExecContext(ctx, startSprint, arg.UserName, arg.ServerName)
	return err
}
