// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sprint_start.sql

package database

import (
	"context"
)

const startSprint = `-- name: StartSprint :exec
BEGIN
`

func (q *Queries) StartSprint(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, startSprint)
	return err
}
